[phases.setup]
nixPkgs = ["nodejs_20", "php", "phpPackages.composer"]
 
[phases.install]
cmds = [
  "composer install --no-scripts --prefer-dist --optimize-autoloader",
  "npm ci",
  "npm run build"
]
 
[start]
cmd = 'sh -c "php -S 0.0.0.0:${PORT} -t public"'